//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HushienBot.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hushienDBEntities : DbContext
    {
        public hushienDBEntities()
            : base("name=hushienDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empathy> Empathies { get; set; }
        public virtual DbSet<Preach> Preaches { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
    }
}
