//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HushienBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preach
    {
        public long id { get; set; }
        public string preachType { get; set; }
        public string preachSentence { get; set; }
    }
}
