//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HushienBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public long id { get; set; }
        public string ModuleChar { get; set; }
        public string ModuleFullName { get; set; }
        public string ModuleClass { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int SlotDay { get; set; }
    }
}
